In [2]:
import numpy as np
import pandas as pd

In [3]:
dt=pd.read_csv(r"D:\datasets\insurance.csv")

In [4]:
dt.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
dt["region"].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [6]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


In [7]:
dt.isnull().any()

age         False
sex         False
bmi         False
children    False
smoker      False
region      False
charges     False
dtype: bool

In [8]:
x=dt.iloc[:,0:6].values
y=dt.iloc[:,6].values

In [9]:
x.shape

(1338, 6)

In [10]:
y.shape

(1338,)

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,4,5])],remainder="passthrough")
#coverts data into binary form

x=ct.fit_transform(x)

In [12]:
x.shape

(1338, 11)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
x_train

array([[0.0, 1.0, 0.0, ..., 37, 34.1, 4],
       [0.0, 1.0, 1.0, ..., 18, 34.43, 0],
       [1.0, 0.0, 0.0, ..., 23, 36.67, 2],
       ...,
       [0.0, 1.0, 1.0, ..., 40, 25.08, 0],
       [0.0, 1.0, 1.0, ..., 19, 35.53, 0],
       [1.0, 0.0, 1.0, ..., 33, 18.5, 1]], dtype=object)

In [15]:
y_train

array([40182.246 ,  1137.4697, 38511.6283, ...,  5415.6612,  1646.4297,
        4766.022 ])

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
ann=Sequential()

In [20]:
ann.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

In [21]:
ann.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [22]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="relu"))

In [23]:
ann.compile("adam","mean_squared_error",metrics=["accuracy"])

In [24]:
ann.fit(x_train,y_train,batch_size=32,epochs=500)

Epoch 1/500
34/34 [==============================] - 4s 7ms/step - loss: 326594220.8000 - accuracy: 0.0000e+00
Epoch 2/500
34/34 [==============================] - 0s 5ms/step - loss: 309945263.0857 - accuracy: 0.0000e+00
Epoch 3/500
34/34 [==============================] - 0s 2ms/step - loss: 314475212.5714 - accuracy: 0.0000e+00
Epoch 4/500
34/34 [==============================] - 0s 2ms/step - loss: 339742074.5143 - accuracy: 0.0000e+00
Epoch 5/500
34/34 [==============================] - 0s 2ms/step - loss: 323408272.0000 - accuracy: 0.0000e+00
Epoch 6/500
34/34 [==============================] - 0s 3ms/step - loss: 315266342.4000 - accuracy: 0.0000e+00
Epoch 7/500
34/34 [==============================] - 0s 3ms/step - loss: 332047257.6000 - accuracy: 0.0000e+00
Epoch 8/500
34/34 [==============================] - 0s 2ms/step - loss: 319832545.8286 - accuracy: 0.0000e+00
Epoch 9/500
34/34 [==============================] - 0s 2ms/step - loss: 304241967.0857 - accuracy: 0.0000e+00
E

34/34 [==============================] - 0s 1ms/step - loss: 35769616.2286 - accuracy: 0.0000e+00
Epoch 148/500
34/34 [==============================] - 0s 1ms/step - loss: 39266632.3429 - accuracy: 0.0000e+00
Epoch 149/500
34/34 [==============================] - 0s 1ms/step - loss: 41712007.6571 - accuracy: 0.0000e+00
Epoch 150/500
34/34 [==============================] - 0s 1ms/step - loss: 34985725.5429 - accuracy: 0.0000e+00
Epoch 151/500
34/34 [==============================] - 0s 1ms/step - loss: 34787888.2857 - accuracy: 0.0000e+00
Epoch 152/500
34/34 [==============================] - 0s 1ms/step - loss: 38247323.3143 - accuracy: 0.0000e+00
Epoch 153/500
34/34 [==============================] - 0s 2ms/step - loss: 39095348.5714 - accuracy: 0.0000e+00
Epoch 154/500
34/34 [==============================] - 0s 2ms/step - loss: 36175457.3714 - accuracy: 0.0000e+00
Epoch 155/500
34/34 [==============================] - 0s 2ms/step - loss: 34216506.8571 - accuracy: 0.0000e+00
Epoch 

34/34 [==============================] - 0s 4ms/step - loss: 30578542.8571 - accuracy: 0.0000e+00
Epoch 293/500
34/34 [==============================] - 0s 4ms/step - loss: 30663770.6286 - accuracy: 0.0000e+00
Epoch 294/500
34/34 [==============================] - 0s 4ms/step - loss: 34041340.1714 - accuracy: 0.0000e+00
Epoch 295/500
34/34 [==============================] - 0s 2ms/step - loss: 37137316.1714 - accuracy: 0.0000e+00
Epoch 296/500
34/34 [==============================] - 0s 2ms/step - loss: 32869609.3143 - accuracy: 0.0000e+00
Epoch 297/500
34/34 [==============================] - 0s 4ms/step - loss: 34328023.5429 - accuracy: 0.0000e+00
Epoch 298/500
34/34 [==============================] - 0s 2ms/step - loss: 29812090.6857 - accuracy: 0.0000e+00
Epoch 299/500
34/34 [==============================] - 0s 2ms/step - loss: 34930912.0571 - accuracy: 0.0000e+00
Epoch 300/500
34/34 [==============================] - 0s 2ms/step - loss: 32115943.8286 - accuracy: 0.0000e+00
Epoch 

34/34 [==============================] - 0s 2ms/step - loss: 35328600.1143 - accuracy: 0.0000e+00
Epoch 438/500
34/34 [==============================] - 0s 3ms/step - loss: 33460765.4857 - accuracy: 0.0000e+00
Epoch 439/500
34/34 [==============================] - 0s 2ms/step - loss: 36010581.9429 - accuracy: 0.0000e+00
Epoch 440/500
34/34 [==============================] - 0s 2ms/step - loss: 34917203.6571 - accuracy: 0.0000e+00
Epoch 441/500
34/34 [==============================] - 0s 2ms/step - loss: 33331993.8286 - accuracy: 0.0000e+00
Epoch 442/500
34/34 [==============================] - 0s 4ms/step - loss: 34502923.3714 - accuracy: 0.0000e+00
Epoch 443/500
34/34 [==============================] - 0s 4ms/step - loss: 32339072.1143 - accuracy: 0.0000e+00
Epoch 444/500
34/34 [==============================] - 0s 4ms/step - loss: 36080305.6000 - accuracy: 0.0000e+00
Epoch 445/500
34/34 [==============================] - 0s 4ms/step - loss: 36534728.3429 - accuracy: 0.0000e+00
Epoch 

In [25]:
ypred=ann.predict(x_test)

In [26]:
ypred

array([[ 9594.103  ],
       [ 9924.816  ],
       [44530.273  ],
       [16292.755  ],
       [ 5403.21   ],
       [ 2479.874  ],
       [ 4267.875  ],
       [14359.892  ],
       [ 8588.411  ],
       [ 7052.329  ],
       [ 5501.449  ],
       [ 9170.376  ],
       [10234.452  ],
       [ 4595.196  ],
       [25702.857  ],
       [10836.989  ],
       [ 8758.679  ],
       [ 5843.374  ],
       [ 7347.0273 ],
       [25253.506  ],
       [32970.9    ],
       [14077.526  ],
       [11756.098  ],
       [31374.854  ],
       [ 4578.187  ],
       [ 8863.186  ],
       [ 2825.224  ],
       [10634.548  ],
       [ 4736.924  ],
       [ 9053.147  ],
       [ 8411.187  ],
       [47620.086  ],
       [15850.121  ],
       [13850.407  ],
       [18518.846  ],
       [ 6301.7354 ],
       [11168.221  ],
       [32421.186  ],
       [34800.855  ],
       [ 6341.283  ],
       [ 4631.4023 ],
       [ 3378.3518 ],
       [29072.746  ],
       [45444.613  ],
       [27555.77   ],
       [ 6

In [27]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [30]:
yp=ann.predict(sc.transform(ct.transform([[19,"female",27.900,0,"yes","southwest"]])))

In [31]:
yp

array([[21200.484]], dtype=float32)