In [1]:
import numpy as np
import pandas as pd

In [2]:
dt=pd.read_csv(r"D:\datasets\Bankloan.csv")

In [3]:
dt.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
dt.isnull().any()

ID                    False
Age                   False
Experience            False
Income                False
ZIP Code              False
Family                False
CCAvg                 False
Education             False
Mortgage              False
Personal Loan         False
Securities Account    False
CD Account            False
Online                False
CreditCard            False
dtype: bool

In [5]:
dt.drop(columns=["ID","ZIP Code"],inplace=True)

In [6]:
dt.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [9]:
x=dt.iloc[:,[0,1,2,3,4,5,6,8,9,10,11]].values
y=dt.iloc[:,7].values

In [10]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
y.shape

(5000,)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
x_train.shape

(4000, 11)

In [15]:
y_train.shape

(4000,)

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [19]:
from tensorflow.keras.models import Sequential #this library is used to initialise the model
from tensorflow.keras.layers import Dense  #used to add layers of ANN

In [20]:
ann=Sequential()

In [21]:
ann.add(Dense(11,kernel_initializer="random_uniform",activation="relu"))

In [22]:
ann.add(Dense(22,kernel_initializer="random_uniform",activation="relu"))

In [23]:
ann.add(Dense(1,kernel_initializer="random_uniform",activation="sigmoid"))

In [24]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [25]:
ann.fit(x_train,y_train,batch_size=32,epochs=20)

Epoch 1/20
125/125 [==============================] - 2s 4ms/step - loss: 0.6288 - accuracy: 0.9017
Epoch 2/20
125/125 [==============================] - 0s 3ms/step - loss: 0.2124 - accuracy: 0.9083
Epoch 3/20
125/125 [==============================] - 0s 3ms/step - loss: 0.1584 - accuracy: 0.9068
Epoch 4/20
125/125 [==============================] - 0s 2ms/step - loss: 0.1300 - accuracy: 0.9252
Epoch 5/20
125/125 [==============================] - 0s 2ms/step - loss: 0.1053 - accuracy: 0.9637
Epoch 6/20
125/125 [==============================] - 0s 2ms/step - loss: 0.0924 - accuracy: 0.9728
Epoch 7/20
125/125 [==============================] - 0s 2ms/step - loss: 0.0862 - accuracy: 0.9719
Epoch 8/20
125/125 [==============================] - 0s 2ms/step - loss: 0.0726 - accuracy: 0.9772
Epoch 9/20
125/125 [==============================] - 0s 3ms/step - loss: 0.0676 - accuracy: 0.9794
Epoch 10/20
125/125 [==============================] - 0s 3ms/step - loss: 0.0711 - accuracy: 0.9752

In [26]:
ypred=ann.predict(x_test)

In [32]:
ypred=ypred>0.5

In [33]:
ypred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [

In [34]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [35]:
yp=ann.predict(sc.transform([[25,1,49,4,1.6,1,0,1,0,0,0]]))

In [36]:
yp

array([[1.8278792e-05]], dtype=float32)

In [37]:
yp>0.5

array([[False]])

In [41]:
yp=ann.predict_classes(sc.transform([[34,9,180,1,8.9,3,0,0,0,0,0]]))

C:\Users\Likki. Abhinay Reddy\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [42]:
yp>0.5

array([[ True]])